Initial project
ls1intum/Hermes pull request #1
Opened 2023-02-17 15:31 UTC by sven0311

2023-05-25 16:53 UTC, Mtze requested changes

2023-05-25 16:53 UTC, Mtze commented on apns/src/main/java/de/tum/cit/artemis/push/artemispushnotificationrelay/apns/ApnsSendService.java
> +        log.info("apnsCertificatePwd: " + apnsCertificatePwd);
I don't think it is a good idea to log the password ;)

2023-05-25 16:55 UTC, bassner commented on firebase/src/main/java/de/tum/cit/artemis/push/artemispushnotificationrelay/firebase/FirebaseSendService.java
> +    }
I'd suggest to return early instead of nesting here

2023-05-25 16:56 UTC, bassner commented on firebase/src/main/java/de/tum/cit/artemis/push/artemispushnotificationrelay/firebase/FirebaseSendService.java
> +        if (firebaseApp.isPresent()) {
I'd suggest to return early instead of nesting here

2023-07-27 10:50 UTC, Mtze approved these changes

2023-07-27 10:51 UTC, merged